# Generated by Django 4.1.2 on 2022-10-16 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='uid',
        ),
    ]
